apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: services
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/krishan-la/sample-argo-cd.git
        revision: HEAD
        directories:
          - path: services/*
  template:
    metadata:
      name: "{{.path.basename}}"
    spec:
      project: "my-project"
      source:
        repoURL: https://github.com/krishan-la/sample-argo-cd.git
        targetRevision: HEAD
        path: "{{.path.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "apps"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
