apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-update-active-capacity
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: app-update-active-capacity
  template:
    metadata:
      labels:
        app: app-update-active-capacity
    spec:
      containers:
      - image: 958689846081.dkr.ecr.us-east-1.amazonaws.com/sample-python-fastapi:latest
        name: app-update-active-capacity
        ports:
        - containerPort: 8000
